#sonar.projectKey=SpringBootProject
#sonar.projectName=SpringBootProject
sonar.projectKey=CheckCodeNew1.4
sonar.projectName=CheckCodeNew1.4
sonar.login=admin
sonar.password=java123
sonar.projectVersion=1.0
sonar.sources=D:\\CodeBaseWorks\\workspace\\MyApp\\src
sonar.language=java
sonar.exclusions=**/*.class
sonar.java.binaries=D:\\CodeBaseWorks\\workspace\\MyApp\\src